### ISSUE TITLE
Font change is not available

### ISSUE THREAD

**Issue by manasa-allen** [mgriebling/SwiftMath#24]
There is no way to change or customize the font. Could you please help me understand how we can change the font?

**Comment by mgriebling** [comment]
It's unclear if you want to add a new font or just switch among the existing build-in fonts.

If adding a new font please see [Adding a font](https://github.com/mgriebling/SwiftMath/issues).
Otherwise, switching between built-in fonts is covered in this [demo](https://github.com/mgriebling/SwiftMathDemo)/
